apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: default
  labels:
    app: ghost
    component: frontend
spec:
  type: ClusterIP # 내부 전용 IP
  selector:
    app: ghost
    component: frontend
  ports:
    - port: 2368 # 서비스 포트 (다른 파드가 접근할 때)
      targetPort: 2368 # 실제 컨테이너 포트
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-mysql
  namespace: default
  labels:
    app: ghost
    component: database
spec:
  type: ClusterIP
  selector:
    app: ghost
    component: database
  ports:
    - port: 3306
      targetPort: 3306
