apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 공식 Sealed Secrets Controller
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.0/controller.yaml
