apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # 인프라 컴포넌트들
  - argocd
  - argocd-image-updater
  - sealed-secrets
  - cert-manager/issuer.yaml
  - traefik/dashboard.yaml
  - traefik/helmchartconfig.yaml
