apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: default
  labels:
    app: n8n
    component: app
spec:
  type: ClusterIP
  selector:
    app: n8n
    component: app
  ports:
    - port: 5678
      targetPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-postgres
  namespace: default
  labels:
    app: n8n
    component: database
spec:
  type: ClusterIP
  selector:
    app: n8n
    component: database
  ports:
    - port: 5432
      targetPort: 5432
