apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - pvc.yaml
  - deployment-hub.yaml
  - deployment-agent.yaml
  - service.yaml
  - ingress.yaml
  - sealed-secret.yaml
