apiVersion: v1
kind: Service
metadata:
  name: beszel-hub
  namespace: default
  labels:
    app: beszel
    component: hub
spec:
  ports:
    - port: 8090
      targetPort: 8090
      name: http
  selector:
    app: beszel
    component: hub
