apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - configmap.yaml
  - middleware.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealed-secret.yaml
